# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('asset', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('layer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_set', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('skew', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('sd', models.FloatField(blank=True, null=True)),
                ('fid', models.IntegerField()),
                ('site', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.DataVariable')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('feature_set', 'date', 'product', 'site')]),
        ),
    ]
