# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 21:05
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0002_auto_20161108_1929'),
    ]

    operations = [
        HStoreExtension(),
    ]
