# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 19:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0003_auto_20161108_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField()),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vector',
            unique_together=set([('name', 'source')]),
        ),
    ]
