# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 19:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0004_auto_20161111_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
