# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0005_vector_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='fid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
