# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0006_vector_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='vector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbinv.Vector'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vector',
            unique_together=set([('fid', 'source')]),
        ),
    ]
