# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0007_auto_20161117_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datavariable',
            name='layer',
        ),
        migrations.AddField(
            model_name='datavariable',
            name='band',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datavariable',
            name='band_number',
            field=models.IntegerField(default=0),
        ),
    ]
