# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0008_auto_20161202_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datavariable',
            old_name='asset',
            new_name='driver',
        ),
    ]
